### ISSUE TITLE
bot has hardcoded usernames for admin

### ISSUE THREAD

**Issue by Dracovious** [fusoyeahhh/BCFantasy#3]
`_ROOT = {"darkslash88"}
# add additional admin names here
_AUTHORIZED = _ROOT | {"fusoyeahhh", "crackboombot"}`

probably best to put users in the config json file rather than hard code it just a security 101 guideline then people can configure the bot at a local level for privilege's over code base.

**Comment by fusoyeahhh** [comment]
Addressed in 27ed70b
